import crypto from "crypto";

const ENC_PREFIX = "enc:v1:";

/**
 * Read a secret from env. Supports plaintext or enc:v1:... (AES-256-GCM).
 * Ciphertext is generated by: node scripts/encrypt-env-secret.mjs
 * Master key: APP_SECRETS_KEY (64 hex chars = 32 bytes).
 */
export function resolveSecret(envName: string): string | undefined {
  const raw = process.env[envName]?.trim();
  if (!raw) return undefined;
  if (!raw.startsWith(ENC_PREFIX)) return raw;

  const master = process.env.APP_SECRETS_KEY?.trim();
  if (!master) {
    throw new Error(
      `${envName} 为加密格式，但未设置 APP_SECRETS_KEY（仅保存在 ECS，勿提交 git）`
    );
  }

  const key = master.length === 64 && /^[0-9a-f]+$/i.test(master)
    ? Buffer.from(master, "hex")
    : crypto.createHash("sha256").update(master, "utf8").digest();

  const packed = Buffer.from(raw.slice(ENC_PREFIX.length), "base64");
  if (packed.length < 12 + 16) {
    throw new Error(`${envName} 加密值格式无效`);
  }
  const iv = packed.subarray(0, 12);
  const tag = packed.subarray(12, 28);
  const ciphertext = packed.subarray(28);

  const plain = crypto.createDecipheriv("aes-256-gcm", key, iv);
  plain.setAuthTag(tag);
  return Buffer.concat([plain.update(ciphertext), plain.final()]).toString("utf8");
}
