/** Manim 模板能力元数据 — 与 manim/template_catalog.py 保持 ID 一致 */

export interface ManimCapability {
  id: string;
  label: string;
  desc: string;
  category: string;
  layer: 1 | 2 | 3;
  primitives: string[];
  officialExample?: { title: string; url: string };
  defaultParams: Record<string, unknown>;
  paramHelp: Record<string, string>;
}

export const MANIM_CAPABILITY_CATEGORIES = [
  { id: "engineering", label: "工程 / 物理 / 电气" },
  { id: "math", label: "数学 / 几何 / 图表" },
  { id: "infographic", label: "信息图表" },
  { id: "text", label: "文本动画" },
  { id: "structure", label: "结构 / 轨道" },
  { id: "english", label: "英语学习" },
  { id: "media", label: "媒体 / 公式 / 3D" },
  { id: "advanced", label: "高级 / 自定义" },
] as const;

export type ManimDomain = "semiconductor" | "learning" | "english" | "media";

export const MANIM_DOMAINS = [
  { id: "semiconductor" as const, label: "半导体 / 工程" },
  { id: "learning" as const, label: "学习 / 记忆" },
  { id: "english" as const, label: "英语学习" },
  { id: "media" as const, label: "媒体 / 公式 / 3D" },
];

/** 成熟应用场景四分类 — 与模板 ID 映射 */
export const TEMPLATE_DOMAIN: Record<string, ManimDomain> = {
  pn_junction: "semiconductor",
  band_structure: "semiconductor",
  current_arrow: "semiconductor",
  photon_breakdown: "semiconductor",
  semiconductor_layers: "semiconductor",
  mosfet_channel: "semiconductor",
  buck_converter: "semiconductor",
  sine_waveform: "semiconductor",
  llc_resonant: "semiconductor",
  circuit_loop: "semiconductor",
  band_temperature: "semiconductor",
  crystal_lattice: "semiconductor",
  isometric_stack: "semiconductor",
  function_graph: "learning",
  coordinate_grid: "learning",
  vector_sum: "learning",
  bar_chart: "learning",
  pie_chart: "learning",
  line_chart_compare: "learning",
  timeline_horizontal: "learning",
  flowchart: "learning",
  forgetting_curve: "learning",
  concept_network: "learning",
  learning_curve: "learning",
  typewriter_text: "learning",
  keyword_pop: "learning",
  formula_steps: "learning",
  chapter_banner: "learning",
  code_highlight: "learning",
  transform_demo: "learning",
  orbit_paths: "learning",
  custom_dsl: "learning",
  custom_python: "learning",
  manim_probability_tree: "learning",
  manim_formula: "learning",
  manim_simulation_chart: "learning",
  vocab_card: "english",
  grammar_highlight: "english",
  dialogue_scene: "english",
  mathtex_formula: "media",
  mathtex_derivation: "media",
  scene_3d_surface: "media",
  scene_3d_orbit: "media",
  image_focus: "media",
  svg_icon: "media",
  video_embed: "media",
};

export function getTemplateDomain(id: string): ManimDomain {
  return TEMPLATE_DOMAIN[id] ?? "learning";
}

const DOC = "https://docs.manim.community/en/stable/examples.html";

export const MANIM_CAPABILITIES: ManimCapability[] = [
  {
    id: "pn_junction",
    label: "PN 结示意图",
    desc: "N/P 型、耗尽层、电流方向",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "Arrow", "FadeIn", "Write", "mk_text"],
    officialExample: { title: "Creating shapes", url: `${DOC}#creating-shapes` },
    defaultParams: { title: "PN Junction", voltage: 9, current: 1 },
    paramHelp: { title: "标题", voltage: "电压 (V)", current: "电流 (A)" },
  },
  {
    id: "band_structure",
    label: "能带结构",
    desc: "导带、价带、载流子运动",
    category: "engineering",
    layer: 1,
    primitives: ["Line", "Dot", "Create", "animate.move_to"],
    officialExample: { title: "Animations", url: `${DOC}#animations` },
    defaultParams: { title: "Band Structure" },
    paramHelp: { title: "标题" },
  },
  {
    id: "current_arrow",
    label: "电流箭头",
    desc: "电阻电路与欧姆定律示意",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "Arrow", "Line", "GrowArrow"],
    defaultParams: { voltage: 9, current: 1, resistance: 9, title: "Ohm Law" },
    paramHelp: { voltage: "电压 V", current: "电流 A", resistance: "电阻 Ω", title: "标题" },
  },
  {
    id: "photon_breakdown",
    label: "光子击穿",
    desc: "光子激发电子跃迁",
    category: "engineering",
    layer: 1,
    primitives: ["Circle", "Arrow", "FadeOut", "animate"],
    defaultParams: { photon_label: "hv" },
    paramHelp: { photon_label: "光子标签" },
  },
  {
    id: "semiconductor_layers",
    label: "半导体层",
    desc: "多层外延结构",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "LaggedStart", "FadeIn"],
    defaultParams: { title: "Semiconductor Layers" },
    paramHelp: { title: "标题" },
  },
  {
    id: "mosfet_channel",
    label: "MOSFET 沟道",
    desc: "G/S/D 与沟道",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "FadeIn", "Write"],
    defaultParams: { title: "MOSFET Channel" },
    paramHelp: { title: "标题" },
  },
  {
    id: "buck_converter",
    label: "Buck 降压拓扑",
    desc: "开关、电感、电容",
    category: "engineering",
    layer: 1,
    primitives: ["Line", "Square", "Create"],
    defaultParams: { title: "Buck Converter" },
    paramHelp: { title: "标题" },
  },
  {
    id: "sine_waveform",
    label: "正弦波形",
    desc: "时域正弦信号",
    category: "engineering",
    layer: 1,
    primitives: ["make_axes", "plot", "Create"],
    officialExample: { title: "Graphing", url: `${DOC}#graphing` },
    defaultParams: { freq: "50Hz", title: "Sine Wave" },
    paramHelp: { freq: "频率标注", title: "标题" },
  },
  {
    id: "llc_resonant",
    label: "LLC 谐振腔",
    desc: "原边/副边与谐振元件",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "DoubleArrow", "Create"],
    defaultParams: { title: "LLC Resonant" },
    paramHelp: { title: "标题" },
  },
  {
    id: "function_graph",
    label: "函数曲线",
    desc: "可配置函数图像",
    category: "math",
    layer: 1,
    primitives: ["make_axes", "plot", "Create", "Write"],
    officialExample: { title: "Sin graph", url: `${DOC}#graphing` },
    defaultParams: { title: "y = sin(x)", label: "sin(x)" },
    paramHelp: { title: "图标题", label: "曲线标签" },
  },
  {
    id: "coordinate_grid",
    label: "坐标系",
    desc: "网格、点与向量",
    category: "math",
    layer: 1,
    primitives: ["make_number_plane", "Dot", "Arrow", "GrowArrow"],
    defaultParams: { title: "Coordinate Grid" },
    paramHelp: { title: "标题" },
  },
  {
    id: "vector_sum",
    label: "向量合成",
    desc: "平行四边形法则",
    category: "math",
    layer: 1,
    primitives: ["Arrow", "GrowArrow"],
    defaultParams: { title: "Vector Sum" },
    paramHelp: { title: "标题" },
  },
  {
    id: "bar_chart",
    label: "柱状图",
    desc: "数据统计柱状图",
    category: "math",
    layer: 1,
    primitives: ["make_bar_chart", "Rectangle", "FadeIn"],
    defaultParams: { title: "Bar Chart", values: [3, 5, 2, 7, 4] },
    paramHelp: { title: "标题", values: "数值数组" },
  },
  {
    id: "pie_chart",
    label: "饼图",
    desc: "占比扇形图",
    category: "math",
    layer: 2,
    primitives: ["Sector", "AnnularSector", "FadeIn"],
    officialExample: { title: "Pie chart style", url: DOC },
    defaultParams: { title: "Pie Chart", values: [30, 25, 20, 25], labels: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", values: "数值", labels: "标签数组" },
  },
  {
    id: "line_chart_compare",
    label: "折线对比",
    desc: "双曲线同图对比",
    category: "math",
    layer: 2,
    primitives: ["make_axes", "plot", "Create"],
    defaultParams: {
      title: "Compare",
      series: [
        { name: "A", values: [1, 3, 2, 5, 4] },
        { name: "B", values: [2, 2, 4, 3, 6] },
      ],
    },
    paramHelp: { title: "标题", series: "系列数组 {name, values}" },
  },
  {
    id: "timeline_horizontal",
    label: "时间轴",
    desc: "横向里程碑",
    category: "infographic",
    layer: 1,
    primitives: ["Line", "Dot", "LaggedStart"],
    defaultParams: { title: "Timeline", events: ["Start", "Phase 1", "Phase 2", "End"] },
    paramHelp: { title: "标题", events: "事件列表" },
  },
  {
    id: "flowchart",
    label: "流程图",
    desc: "纵向步骤",
    category: "infographic",
    layer: 1,
    primitives: ["RoundedRectangle", "Arrow", "GrowArrow"],
    defaultParams: { title: "Flowchart", steps: ["Input", "Process", "Output"] },
    paramHelp: { title: "标题", steps: "步骤列表" },
  },
  {
    id: "forgetting_curve",
    label: "遗忘曲线",
    desc: "记忆衰减曲线",
    category: "infographic",
    layer: 1,
    primitives: ["make_axes", "plot", "exp decay"],
    defaultParams: { title: "Forgetting Curve", x_label: "Time", y_label: "Retention" },
    paramHelp: { title: "标题", x_label: "X轴", y_label: "Y轴" },
  },
  {
    id: "concept_network",
    label: "概念网络",
    desc: "中心辐射节点",
    category: "infographic",
    layer: 1,
    primitives: ["Circle", "Line", "LaggedStart"],
    defaultParams: { title: "Concept Network", center: "Core", nodes: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", center: "中心词", nodes: "周围节点" },
  },
  {
    id: "learning_curve",
    label: "学习效率曲线",
    desc: "理解优先长期留存",
    category: "infographic",
    layer: 1,
    primitives: ["make_axes", "plot"],
    defaultParams: { title: "Learning Curve", hint: "Understand first" },
    paramHelp: { title: "标题", hint: "底部提示" },
  },
  {
    id: "typewriter_text",
    label: "逐字出现",
    desc: "打字机文本",
    category: "text",
    layer: 1,
    primitives: ["AddTextLetterByLetter", "Write"],
    defaultParams: { text: "Active Recall", subtitle: "Learning", highlight: ["关键词"] },
    paramHelp: {
      text: "正文（可写在镜头根级 text 字段）",
      subtitle: "副标题",
      highlight: "高亮关键词字符串数组",
    },
  },
  {
    id: "keyword_pop",
    label: "关键词高亮",
    desc: "关键词弹出",
    category: "text",
    layer: 1,
    primitives: ["FadeIn", "animate.scale"],
    defaultParams: { title: "Keywords", keywords: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", keywords: "关键词数组" },
  },
  {
    id: "formula_steps",
    label: "公式拆解",
    desc: "分步公式",
    category: "text",
    layer: 1,
    primitives: ["FadeIn", "shift"],
    defaultParams: { title: "Formulas", steps: ["P = V * I", "V = I * R", "P = I^2 * R"] },
    paramHelp: { title: "标题", steps: "公式步骤" },
  },
  {
    id: "chapter_banner",
    label: "章节横幅",
    desc: "章节标题",
    category: "text",
    layer: 1,
    primitives: ["Rectangle", "Write", "FadeIn"],
    defaultParams: { chapter: "Chapter 1", title: "Semiconductor" },
    paramHelp: { chapter: "章节号", title: "主标题" },
  },
  {
    id: "isometric_stack",
    label: "层叠结构",
    desc: "伪3D 层叠",
    category: "structure",
    layer: 1,
    primitives: ["Polygon", "LaggedStart"],
    defaultParams: { title: "Layer Stack" },
    paramHelp: { title: "标题" },
  },
  {
    id: "orbit_paths",
    label: "轨道路径",
    desc: "MoveAlongPath 圆周运动",
    category: "structure",
    layer: 1,
    primitives: ["Circle", "MoveAlongPath", "Dot"],
    officialExample: { title: "MoveAlongPath", url: DOC },
    defaultParams: { title: "Orbit Paths" },
    paramHelp: { title: "标题" },
  },
  {
    id: "circuit_loop",
    label: "完整电路回路",
    desc: "电源-电阻-负载闭合回路",
    category: "engineering",
    layer: 2,
    primitives: ["Line", "Rectangle", "Arrow", "Create"],
    defaultParams: { title: "Circuit Loop", voltage: "12V", component: "R1" },
    paramHelp: { title: "标题", voltage: "电源电压", component: "元件名" },
  },
  {
    id: "band_temperature",
    label: "能带随温度",
    desc: "温度升高禁带变窄示意",
    category: "engineering",
    layer: 2,
    primitives: ["Line", "animate", "mk_text"],
    defaultParams: { title: "Band vs Temperature", temp_start: "300K", temp_end: "400K" },
    paramHelp: { title: "标题", temp_start: "起始温度", temp_end: "结束温度" },
  },
  {
    id: "crystal_lattice",
    label: "晶体点阵",
    desc: "伪3D 晶格结构",
    category: "structure",
    layer: 2,
    primitives: ["Dot", "Line", "Polygon", "LaggedStart"],
    defaultParams: { title: "Crystal Lattice", rows: 4, cols: 4 },
    paramHelp: { title: "标题", rows: "行数", cols: "列数" },
  },
  {
    id: "code_highlight",
    label: "代码高亮",
    desc: "逐行代码展示",
    category: "text",
    layer: 2,
    primitives: ["Rectangle", "FadeIn", "mk_text"],
    defaultParams: {
      title: "Code",
      lines: ["def learn():", "    return 'active recall'", "learn()"],
      highlight_line: 2,
    },
    paramHelp: { title: "标题", lines: "代码行数组", highlight_line: "高亮行号(1-based)" },
  },
  {
    id: "transform_demo",
    label: "变换动画",
    desc: "Transform / ReplacementTransform 演示",
    category: "advanced",
    layer: 2,
    primitives: ["Transform", "ReplacementTransform", "Square", "Circle"],
    officialExample: { title: "Transform", url: `${DOC}#transformations` },
    defaultParams: { title: "Transform Demo", from_shape: "square", to_shape: "circle" },
    paramHelp: { title: "标题", from_shape: "square|circle", to_shape: "square|circle" },
  },
  {
    id: "mathtex_formula",
    label: "MathTex 公式",
    desc: "LaTeX 公式展示；无 texlive 时自动文本降级",
    category: "media",
    layer: 2,
    primitives: ["MathTex", "mk_mathtex", "Write"],
    officialExample: { title: "MathTex", url: `${DOC}#mathtex` },
    defaultParams: { title: "Formula", formula: "E = mc^2", caption: "" },
    paramHelp: { title: "标题", formula: "LaTeX 公式", caption: "底部说明（可选）" },
  },
  {
    id: "mathtex_derivation",
    label: "公式推导",
    desc: "分步 MathTex 推导链",
    category: "media",
    layer: 2,
    primitives: ["MathTex", "mk_mathtex", "Write", "VGroup"],
    defaultParams: { title: "Derivation", steps: ["V = IR", "I = \\frac{V}{R}", "P = VI"] },
    paramHelp: { title: "标题", steps: "LaTeX 步骤数组" },
  },
  {
    id: "scene_3d_surface",
    label: "3D 曲面",
    desc: "ThreeDScene 曲面 + 相机环绕（需 OpenGL/xvfb）",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Surface", "ThreeDAxes", "ambient_camera_rotation"],
    defaultParams: { title: "3D Surface" },
    paramHelp: { title: "标题" },
  },
  {
    id: "scene_3d_orbit",
    label: "3D 轨道运动",
    desc: "ThreeDScene 中 MoveAlongPath 轨道演示",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Dot3D", "MoveAlongPath", "Circle"],
    defaultParams: { title: "3D Orbit", label: "Orbit" },
    paramHelp: { title: "标题", label: "角标文字" },
  },
  {
    id: "image_focus",
    label: "图片聚焦",
    desc: "ImageMobject / SVG 图片展示与缩放",
    category: "media",
    layer: 2,
    primitives: ["ImageMobject", "SVGMobject", "FadeIn", "animate.scale"],
    defaultParams: { title: "Image", imagePath: "icon.svg", caption: "" },
    paramHelp: { title: "标题", imagePath: "相对路径或 /files/... URL", caption: "说明文字" },
  },
  {
    id: "svg_icon",
    label: "SVG 图标",
    desc: "SVGMobject 矢量图标动画",
    category: "media",
    layer: 2,
    primitives: ["SVGMobject", "FadeIn", "animate.scale"],
    defaultParams: { title: "SVG", svgPath: "icon.svg", scale: 2.5 },
    paramHelp: { title: "标题", svgPath: "SVG 路径", scale: "缩放倍数" },
  },
  {
    id: "video_embed",
    label: "视频嵌入",
    desc: "VideoMobject 片段嵌入场景",
    category: "media",
    layer: 2,
    primitives: ["VideoMobject", "FadeIn"],
    defaultParams: { title: "Video Clip", videoPath: "", max_duration: 3 },
    paramHelp: { title: "标题", videoPath: "视频路径", max_duration: "最长播放秒数" },
  },
  {
    id: "vocab_card",
    label: "单词卡",
    desc: "词汇、音标、释义与例句卡片",
    category: "english",
    layer: 2,
    primitives: ["RoundedRectangle", "AddTextLetterByLetter", "Write"],
    defaultParams: {
      title: "Vocabulary",
      word: "recall",
      phonetic: "/rI'ko:l/",
      meaning: "to remember",
      example: "Active recall improves memory.",
    },
    paramHelp: { title: "标题", word: "单词", phonetic: "音标", meaning: "释义", example: "例句" },
  },
  {
    id: "grammar_highlight",
    label: "语法高亮",
    desc: "句型模式 + 例句 + 关键词强调",
    category: "english",
    layer: 2,
    primitives: ["SurroundingRectangle", "Indicate", "Write"],
    defaultParams: {
      title: "Grammar",
      pattern: "S + V + O",
      sentence: "I love learning English.",
      highlight: "love",
    },
    paramHelp: { title: "标题", pattern: "句型", sentence: "例句", highlight: "高亮词" },
  },
  {
    id: "dialogue_scene",
    label: "对话场景",
    desc: "双人气泡对话逐条出现",
    category: "english",
    layer: 2,
    primitives: ["RoundedRectangle", "FadeIn", "Write"],
    defaultParams: {
      title: "Dialogue",
      lines: [
        { speaker: "A", text: "How do you study vocabulary?" },
        { speaker: "B", text: "I use active recall and spaced repetition." },
      ],
    },
    paramHelp: { title: "标题", lines: "对话数组 {speaker, text}" },
  },
  {
    id: "manim_probability_tree",
    label: "概率树状图",
    desc: "蒙提霍尔 / 贝叶斯分支路径与概率",
    category: "math",
    layer: 2,
    primitives: ["Line", "VGroup", "FadeIn", "Write"],
    defaultParams: {
      title: "概率树",
      branches: [
        { path: "选中汽车 → 不换赢", prob: "1/3" },
        { path: "选中山羊 → 换门赢", prob: "2/3" },
      ],
      highlight: "2/3 换门胜率",
    },
    paramHelp: {
      title: "标题",
      branches: "分支数组 {path, prob}",
      highlight: "高亮说明文字",
    },
  },
  {
    id: "manim_formula",
    label: "公式推导卡",
    desc: "主公式 + 分步文字推导",
    category: "math",
    layer: 2,
    primitives: ["Write", "FadeIn", "mk_text"],
    defaultParams: {
      title: "贝叶斯推导",
      formula: "P(赢车|换门) = 2/3",
      steps: ["第一次选中汽车概率 = 1/3", "第一次选中山羊概率 = 2/3"],
    },
    paramHelp: { title: "标题", formula: "主公式", steps: "推导步骤字符串数组" },
  },
  {
    id: "manim_simulation_chart",
    label: "模拟实验图表",
    desc: "蒙特卡洛胜率收敛曲线",
    category: "math",
    layer: 2,
    primitives: ["make_axes", "plot", "DashedLine"],
    defaultParams: {
      title: "蒙特卡洛模拟",
      trials: 10000,
      chartType: "line",
      targetValue: 0.666,
      description: "模拟胜率收敛到 66.6%",
    },
    paramHelp: {
      title: "标题",
      trials: "模拟次数（展示用）",
      targetValue: "目标收敛值 0~1",
      description: "底部说明文字",
    },
  },
  {
    id: "custom_dsl",
    label: "JSON 场景 DSL",
    desc: "用 JSON 描述对象与动画序列（第三层）",
    category: "advanced",
    layer: 3,
    primitives: ["JSON-driven", "FadeIn", "Create", "Write", "GrowArrow"],
    officialExample: { title: "Manim examples", url: DOC },
    defaultParams: {
      title: "DSL Demo",
      objects: [
        { id: "c1", type: "circle", radius: 1, color: "BLUE" },
        { id: "t1", type: "text", content: "Hello Manim", shift: [0, -2, 0] },
      ],
      timeline: [
        { action: "create", target: "c1" },
        { action: "write", target: "t1" },
        { action: "wait", duration: 0.5 },
      ],
    },
    paramHelp: {
      title: "场景标题",
      objects: "对象列表 type: circle|rect|text|arrow|dot",
      timeline: "动画序列 action: create|fade_in|write|grow_arrow|wait|transform",
    },
  },
  {
    id: "custom_python",
    label: "自定义 Python Scene",
    desc: "粘贴 Manim Scene 代码（参考官方示例）",
    category: "advanced",
    layer: 3,
    primitives: ["Scene", "construct", "任意 Manim API"],
    officialExample: { title: "Official examples", url: DOC },
    defaultParams: {
      class_name: "CustomScene",
      code: "class CustomScene(Scene):\n    def construct(self):\n        c = Circle()\n        self.play(Create(c))\n        self.wait(1)\n",
    },
    paramHelp: {
      class_name: "Scene 类名",
      code: "完整 Python 代码，必须含 class X(Scene) 与 construct",
    },
  },
];

export function getCapability(id: string): ManimCapability | undefined {
  return MANIM_CAPABILITIES.find((c) => c.id === id);
}

export function getExampleParams(id: string): Record<string, unknown> {
  const cap = getCapability(id);
  return cap ? JSON.parse(JSON.stringify(cap.defaultParams)) : {};
}

/** 按成熟应用场景筛选模板 */
export function getCapabilitiesByDomain(domain: ManimDomain | "all"): ManimCapability[] {
  if (domain === "all") return MANIM_CAPABILITIES;
  return MANIM_CAPABILITIES.filter((c) => getTemplateDomain(c.id) === domain);
}
