/** Manim 模板能力元数据 — 与 manim/template_catalog.py 保持 ID 一致 */

export interface ManimCapability {
  id: string;
  label: string;
  desc: string;
  category: string;
  layer: 1 | 2 | 3;
  primitives: string[];
  officialExample?: { title: string; url: string };
  defaultParams: Record<string, unknown>;
  paramHelp: Record<string, string>;
}

export const MANIM_CAPABILITY_CATEGORIES = [
  { id: "engineering", label: "工程 / 物理 / 电气" },
  { id: "math", label: "数学 / 几何 / 图表" },
  { id: "infographic", label: "信息图表" },
  { id: "text", label: "文本动画" },
  { id: "structure", label: "结构 / 轨道" },
  { id: "english", label: "英语学习" },
  { id: "media", label: "媒体 / 公式 / 3D" },
  { id: "advanced", label: "高级 / 自定义" },
] as const;

export type ManimDomain = "semiconductor" | "learning" | "english" | "media";

export const MANIM_DOMAINS = [
  { id: "semiconductor" as const, label: "半导体 / 工程" },
  { id: "learning" as const, label: "学习 / 记忆" },
  { id: "english" as const, label: "英语学习" },
  { id: "media" as const, label: "媒体 / 公式 / 3D" },
];

/** 成熟应用场景四分类 — 与模板 ID 映射 */
export const TEMPLATE_DOMAIN: Record<string, ManimDomain> = {
  pn_junction: "semiconductor",
  band_structure: "semiconductor",
  current_arrow: "semiconductor",
  photon_breakdown: "semiconductor",
  semiconductor_layers: "semiconductor",
  mosfet_channel: "semiconductor",
  buck_converter: "semiconductor",
  sine_waveform: "semiconductor",
  llc_resonant: "semiconductor",
  circuit_loop: "semiconductor",
  band_temperature: "semiconductor",
  crystal_lattice: "semiconductor",
  isometric_stack: "semiconductor",
  function_graph: "learning",
  coordinate_grid: "learning",
  vector_sum: "learning",
  bar_chart: "learning",
  pie_chart: "learning",
  line_chart_compare: "learning",
  timeline_horizontal: "learning",
  flowchart: "learning",
  forgetting_curve: "learning",
  concept_network: "learning",
  learning_curve: "learning",
  typewriter_text: "learning",
  keyword_pop: "learning",
  formula_steps: "learning",
  chapter_banner: "learning",
  code_highlight: "learning",
  transform_demo: "learning",
  orbit_paths: "learning",
  custom_dsl: "learning",
  custom_python: "learning",
  manim_probability_tree: "learning",
  manim_formula: "learning",
  manim_simulation_chart: "learning",
  manim_cardioid: "learning",
  manim_rose_curve: "learning",
  manim_archimedean_spiral: "learning",
  manim_exponential_spiral: "learning",
  manim_lemniscate: "learning",
  manim_cycloid: "learning",
  manim_lissajous: "learning",
  manim_lorenz_attractor: "media",
  manim_mandelbrot_zoom: "learning",
  manim_custom: "media",
  manim_curve_3d: "media",
  manim_parametric_surface: "media",
  manim_parametric_curve: "learning",
  manim_rossler: "media",
  manim_julia_set: "learning",
  manim_koch_snowflake: "learning",
  manim_three_body: "learning",
  manim_outline: "learning",
  manim_teacher_resources: "learning",
  manim_draw_diagram: "learning",
  manim_compare_table: "learning",
  manim_vocabulary_focus: "learning",
  manim_multi_explanation: "learning",
  manim_explanation_highlight: "learning",
  manim_recall_page: "learning",
  manim_phone_fade: "learning",
  manim_keybook: "learning",
  manim_moving_frame_box: "learning",
  manim_point_with_trace: "media",
  manim_vector_arrow: "learning",
  manim_brace_annotation: "learning",
  manim_sin_cos_plot: "learning",
  manim_point_on_path: "learning",
  manim_moving_angle: "learning",
  manim_sine_unit_circle: "learning",
  manim_boolean_ops: "learning",
  manim_following_camera: "media",
  manim_graph_area: "learning",
  manim_heat_diagram: "learning",
  formula_curve: "media",
  vocab_card: "english",
  grammar_highlight: "english",
  dialogue_scene: "english",
  mathtex_formula: "media",
  mathtex_derivation: "media",
  scene_3d_surface: "media",
  scene_3d_orbit: "media",
  image_focus: "media",
  svg_icon: "media",
  video_embed: "media",
};

export function getTemplateDomain(id: string): ManimDomain {
  return TEMPLATE_DOMAIN[id] ?? "learning";
}

const DOC = "https://docs.manim.community/en/stable/examples.html";

export const MANIM_CAPABILITIES: ManimCapability[] = [
  {
    id: "pn_junction",
    label: "PN 结示意图",
    desc: "N/P 型、耗尽层、电流方向",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "Arrow", "FadeIn", "Write", "mk_text"],
    officialExample: { title: "Creating shapes", url: `${DOC}#creating-shapes` },
    defaultParams: { title: "PN Junction", voltage: 9, current: 1 },
    paramHelp: { title: "标题", voltage: "电压 (V)", current: "电流 (A)" },
  },
  {
    id: "band_structure",
    label: "能带结构",
    desc: "导带、价带、载流子运动",
    category: "engineering",
    layer: 1,
    primitives: ["Line", "Dot", "Create", "animate.move_to"],
    officialExample: { title: "Animations", url: `${DOC}#animations` },
    defaultParams: { title: "Band Structure" },
    paramHelp: { title: "标题" },
  },
  {
    id: "current_arrow",
    label: "电流箭头",
    desc: "电阻电路与欧姆定律示意",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "Arrow", "Line", "GrowArrow"],
    defaultParams: { voltage: 9, current: 1, resistance: 9, title: "Ohm Law" },
    paramHelp: { voltage: "电压 V", current: "电流 A", resistance: "电阻 Ω", title: "标题" },
  },
  {
    id: "photon_breakdown",
    label: "光子击穿",
    desc: "光子激发电子跃迁",
    category: "engineering",
    layer: 1,
    primitives: ["Circle", "Arrow", "FadeOut", "animate"],
    defaultParams: { photon_label: "hv" },
    paramHelp: { photon_label: "光子标签" },
  },
  {
    id: "semiconductor_layers",
    label: "半导体层",
    desc: "多层外延结构",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "LaggedStart", "FadeIn"],
    defaultParams: { title: "Semiconductor Layers" },
    paramHelp: { title: "标题" },
  },
  {
    id: "mosfet_channel",
    label: "MOSFET 沟道",
    desc: "G/S/D 与沟道",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "FadeIn", "Write"],
    defaultParams: { title: "MOSFET Channel" },
    paramHelp: { title: "标题" },
  },
  {
    id: "buck_converter",
    label: "Buck 降压拓扑",
    desc: "开关、电感、电容",
    category: "engineering",
    layer: 1,
    primitives: ["Line", "Square", "Create"],
    defaultParams: { title: "Buck Converter" },
    paramHelp: { title: "标题" },
  },
  {
    id: "sine_waveform",
    label: "正弦波形",
    desc: "时域正弦信号",
    category: "engineering",
    layer: 1,
    primitives: ["make_axes", "plot", "Create"],
    officialExample: { title: "Graphing", url: `${DOC}#graphing` },
    defaultParams: { freq: "50Hz", title: "Sine Wave" },
    paramHelp: { freq: "频率标注", title: "标题" },
  },
  {
    id: "llc_resonant",
    label: "LLC 谐振腔",
    desc: "原边/副边与谐振元件",
    category: "engineering",
    layer: 1,
    primitives: ["Rectangle", "DoubleArrow", "Create"],
    defaultParams: { title: "LLC Resonant" },
    paramHelp: { title: "标题" },
  },
  {
    id: "function_graph",
    label: "函数曲线",
    desc: "可配置函数图像",
    category: "math",
    layer: 1,
    primitives: ["make_axes", "plot", "Create", "Write"],
    officialExample: { title: "Sin graph", url: `${DOC}#graphing` },
    defaultParams: { title: "y = sin(x)", label: "sin(x)" },
    paramHelp: { title: "图标题", label: "曲线标签" },
  },
  {
    id: "coordinate_grid",
    label: "坐标系",
    desc: "网格、点与向量",
    category: "math",
    layer: 1,
    primitives: ["make_number_plane", "Dot", "Arrow", "GrowArrow"],
    defaultParams: { title: "Coordinate Grid" },
    paramHelp: { title: "标题" },
  },
  {
    id: "vector_sum",
    label: "向量合成",
    desc: "平行四边形法则",
    category: "math",
    layer: 1,
    primitives: ["Arrow", "GrowArrow"],
    defaultParams: { title: "Vector Sum" },
    paramHelp: { title: "标题" },
  },
  {
    id: "bar_chart",
    label: "柱状图",
    desc: "数据统计柱状图",
    category: "math",
    layer: 1,
    primitives: ["make_bar_chart", "Rectangle", "FadeIn"],
    defaultParams: { title: "Bar Chart", values: [3, 5, 2, 7, 4] },
    paramHelp: { title: "标题", values: "数值数组" },
  },
  {
    id: "pie_chart",
    label: "饼图",
    desc: "占比扇形图",
    category: "math",
    layer: 2,
    primitives: ["Sector", "AnnularSector", "FadeIn"],
    officialExample: { title: "Pie chart style", url: DOC },
    defaultParams: { title: "Pie Chart", values: [30, 25, 20, 25], labels: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", values: "数值", labels: "标签数组" },
  },
  {
    id: "line_chart_compare",
    label: "折线对比",
    desc: "双曲线同图对比",
    category: "math",
    layer: 2,
    primitives: ["make_axes", "plot", "Create"],
    defaultParams: {
      title: "Compare",
      series: [
        { name: "A", values: [1, 3, 2, 5, 4] },
        { name: "B", values: [2, 2, 4, 3, 6] },
      ],
    },
    paramHelp: { title: "标题", series: "系列数组 {name, values}" },
  },
  {
    id: "timeline_horizontal",
    label: "时间轴",
    desc: "横向里程碑",
    category: "infographic",
    layer: 1,
    primitives: ["Line", "Dot", "LaggedStart"],
    defaultParams: { title: "Timeline", events: ["Start", "Phase 1", "Phase 2", "End"] },
    paramHelp: { title: "标题", events: "事件列表" },
  },
  {
    id: "flowchart",
    label: "流程图",
    desc: "纵向步骤",
    category: "infographic",
    layer: 1,
    primitives: ["RoundedRectangle", "Arrow", "GrowArrow"],
    defaultParams: { title: "Flowchart", steps: ["Input", "Process", "Output"] },
    paramHelp: { title: "标题", steps: "步骤列表" },
  },
  {
    id: "forgetting_curve",
    label: "遗忘曲线",
    desc: "记忆衰减曲线",
    category: "infographic",
    layer: 1,
    primitives: ["make_axes", "plot", "exp decay"],
    defaultParams: { title: "Forgetting Curve", x_label: "Time", y_label: "Retention" },
    paramHelp: { title: "标题", x_label: "X轴", y_label: "Y轴" },
  },
  {
    id: "concept_network",
    label: "概念网络",
    desc: "中心辐射节点",
    category: "infographic",
    layer: 1,
    primitives: ["Circle", "Line", "LaggedStart"],
    defaultParams: { title: "Concept Network", center: "Core", nodes: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", center: "中心词", nodes: "周围节点" },
  },
  {
    id: "learning_curve",
    label: "学习效率曲线",
    desc: "理解优先长期留存",
    category: "infographic",
    layer: 1,
    primitives: ["make_axes", "plot"],
    defaultParams: { title: "Learning Curve", hint: "Understand first" },
    paramHelp: { title: "标题", hint: "底部提示" },
  },
  {
    id: "typewriter_text",
    label: "逐字出现",
    desc: "打字机文本",
    category: "text",
    layer: 1,
    primitives: ["AddTextLetterByLetter", "Write"],
    defaultParams: { text: "Active Recall", subtitle: "Learning", highlight: ["关键词"] },
    paramHelp: {
      text: "正文（可写在镜头根级 text 字段）",
      subtitle: "副标题",
      highlight: "高亮关键词字符串数组",
    },
  },
  {
    id: "keyword_pop",
    label: "关键词高亮",
    desc: "关键词弹出",
    category: "text",
    layer: 1,
    primitives: ["FadeIn", "animate.scale"],
    defaultParams: { title: "Keywords", keywords: ["A", "B", "C", "D"] },
    paramHelp: { title: "标题", keywords: "关键词数组" },
  },
  {
    id: "formula_steps",
    label: "公式拆解",
    desc: "分步公式",
    category: "text",
    layer: 1,
    primitives: ["FadeIn", "shift"],
    defaultParams: { title: "Formulas", steps: ["P = V * I", "V = I * R", "P = I^2 * R"] },
    paramHelp: { title: "标题", steps: "公式步骤" },
  },
  {
    id: "chapter_banner",
    label: "章节横幅",
    desc: "章节标题",
    category: "text",
    layer: 1,
    primitives: ["Rectangle", "Write", "FadeIn"],
    defaultParams: { chapter: "Chapter 1", title: "Semiconductor" },
    paramHelp: { chapter: "章节号", title: "主标题" },
  },
  {
    id: "isometric_stack",
    label: "层叠结构",
    desc: "伪3D 层叠",
    category: "structure",
    layer: 1,
    primitives: ["Polygon", "LaggedStart"],
    defaultParams: { title: "Layer Stack" },
    paramHelp: { title: "标题" },
  },
  {
    id: "orbit_paths",
    label: "轨道路径",
    desc: "MoveAlongPath 圆周运动",
    category: "structure",
    layer: 1,
    primitives: ["Circle", "MoveAlongPath", "Dot"],
    officialExample: { title: "MoveAlongPath", url: DOC },
    defaultParams: { title: "Orbit Paths" },
    paramHelp: { title: "标题" },
  },
  {
    id: "circuit_loop",
    label: "完整电路回路",
    desc: "电源-电阻-负载闭合回路",
    category: "engineering",
    layer: 2,
    primitives: ["Line", "Rectangle", "Arrow", "Create"],
    defaultParams: { title: "Circuit Loop", voltage: "12V", component: "R1" },
    paramHelp: { title: "标题", voltage: "电源电压", component: "元件名" },
  },
  {
    id: "band_temperature",
    label: "能带随温度",
    desc: "温度升高禁带变窄示意",
    category: "engineering",
    layer: 2,
    primitives: ["Line", "animate", "mk_text"],
    defaultParams: { title: "Band vs Temperature", temp_start: "300K", temp_end: "400K" },
    paramHelp: { title: "标题", temp_start: "起始温度", temp_end: "结束温度" },
  },
  {
    id: "crystal_lattice",
    label: "晶体点阵",
    desc: "伪3D 晶格结构",
    category: "structure",
    layer: 2,
    primitives: ["Dot", "Line", "Polygon", "LaggedStart"],
    defaultParams: { title: "Crystal Lattice", rows: 4, cols: 4 },
    paramHelp: { title: "标题", rows: "行数", cols: "列数" },
  },
  {
    id: "code_highlight",
    label: "代码高亮",
    desc: "逐行代码展示",
    category: "text",
    layer: 2,
    primitives: ["Rectangle", "FadeIn", "mk_text"],
    defaultParams: {
      title: "Code",
      lines: ["def learn():", "    return 'active recall'", "learn()"],
      highlight_line: 2,
    },
    paramHelp: { title: "标题", lines: "代码行数组", highlight_line: "高亮行号(1-based)" },
  },
  {
    id: "transform_demo",
    label: "变换动画",
    desc: "Transform / ReplacementTransform 演示",
    category: "advanced",
    layer: 2,
    primitives: ["Transform", "ReplacementTransform", "Square", "Circle"],
    officialExample: { title: "Transform", url: `${DOC}#transformations` },
    defaultParams: { title: "Transform Demo", from_shape: "square", to_shape: "circle" },
    paramHelp: { title: "标题", from_shape: "square|circle", to_shape: "square|circle" },
  },
  {
    id: "mathtex_formula",
    label: "MathTex 公式",
    desc: "LaTeX 公式展示；无 texlive 时自动文本降级",
    category: "media",
    layer: 2,
    primitives: ["MathTex", "mk_mathtex", "Write"],
    officialExample: { title: "MathTex", url: `${DOC}#mathtex` },
    defaultParams: { title: "Formula", formula: "E = mc^2", caption: "" },
    paramHelp: { title: "标题", formula: "LaTeX 公式", caption: "底部说明（可选）" },
  },
  {
    id: "mathtex_derivation",
    label: "公式推导",
    desc: "分步 MathTex 推导链",
    category: "media",
    layer: 2,
    primitives: ["MathTex", "mk_mathtex", "Write", "VGroup"],
    defaultParams: { title: "Derivation", steps: ["V = IR", "I = \\frac{V}{R}", "P = VI"] },
    paramHelp: { title: "标题", steps: "LaTeX 步骤数组" },
  },
  {
    id: "scene_3d_surface",
    label: "3D 曲面",
    desc: "ThreeDScene 曲面 + 相机环绕（需 OpenGL/xvfb）",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Surface", "ThreeDAxes", "ambient_camera_rotation"],
    defaultParams: { title: "3D Surface" },
    paramHelp: { title: "标题" },
  },
  {
    id: "scene_3d_orbit",
    label: "3D 轨道运动",
    desc: "ThreeDScene 中 MoveAlongPath 轨道演示",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Dot3D", "MoveAlongPath", "Circle"],
    defaultParams: { title: "3D Orbit", label: "Orbit" },
    paramHelp: { title: "标题", label: "角标文字" },
  },
  {
    id: "image_focus",
    label: "图片聚焦",
    desc: "ImageMobject / SVG 图片展示与缩放",
    category: "media",
    layer: 2,
    primitives: ["ImageMobject", "SVGMobject", "FadeIn", "animate.scale"],
    defaultParams: { title: "Image", imagePath: "icon.svg", caption: "" },
    paramHelp: { title: "标题", imagePath: "相对路径或 /files/... URL", caption: "说明文字" },
  },
  {
    id: "svg_icon",
    label: "SVG 图标",
    desc: "SVGMobject 矢量图标动画",
    category: "media",
    layer: 2,
    primitives: ["SVGMobject", "FadeIn", "animate.scale"],
    defaultParams: { title: "SVG", svgPath: "icon.svg", scale: 2.5 },
    paramHelp: { title: "标题", svgPath: "SVG 路径", scale: "缩放倍数" },
  },
  {
    id: "video_embed",
    label: "视频嵌入",
    desc: "VideoMobject 片段嵌入场景",
    category: "media",
    layer: 2,
    primitives: ["VideoMobject", "FadeIn"],
    defaultParams: { title: "Video Clip", videoPath: "", max_duration: 3 },
    paramHelp: { title: "标题", videoPath: "视频路径", max_duration: "最长播放秒数" },
  },
  {
    id: "vocab_card",
    label: "单词卡",
    desc: "词汇、音标、释义与例句卡片",
    category: "english",
    layer: 2,
    primitives: ["RoundedRectangle", "AddTextLetterByLetter", "Write"],
    defaultParams: {
      title: "Vocabulary",
      word: "recall",
      phonetic: "/rI'ko:l/",
      meaning: "to remember",
      example: "Active recall improves memory.",
    },
    paramHelp: { title: "标题", word: "单词", phonetic: "音标", meaning: "释义", example: "例句" },
  },
  {
    id: "grammar_highlight",
    label: "语法高亮",
    desc: "句型模式 + 例句 + 关键词强调",
    category: "english",
    layer: 2,
    primitives: ["SurroundingRectangle", "Indicate", "Write"],
    defaultParams: {
      title: "Grammar",
      pattern: "S + V + O",
      sentence: "I love learning English.",
      highlight: "love",
    },
    paramHelp: { title: "标题", pattern: "句型", sentence: "例句", highlight: "高亮词" },
  },
  {
    id: "dialogue_scene",
    label: "对话场景",
    desc: "双人气泡对话逐条出现",
    category: "english",
    layer: 2,
    primitives: ["RoundedRectangle", "FadeIn", "Write"],
    defaultParams: {
      title: "Dialogue",
      lines: [
        { speaker: "A", text: "How do you study vocabulary?" },
        { speaker: "B", text: "I use active recall and spaced repetition." },
      ],
    },
    paramHelp: { title: "标题", lines: "对话数组 {speaker, text}" },
  },
  {
    id: "manim_probability_tree",
    label: "概率树状图",
    desc: "蒙提霍尔 / 贝叶斯分支路径与概率",
    category: "math",
    layer: 2,
    primitives: ["Line", "VGroup", "FadeIn", "Write"],
    defaultParams: {
      title: "概率树",
      branches: [
        { path: "选中汽车 → 不换赢", prob: "1/3" },
        { path: "选中山羊 → 换门赢", prob: "2/3" },
      ],
      highlight: "2/3 换门胜率",
    },
    paramHelp: {
      title: "标题",
      branches: "分支数组 {path, prob}",
      highlight: "高亮说明文字",
    },
  },
  {
    id: "manim_formula",
    label: "公式推导卡",
    desc: "主公式 + 分步文字推导",
    category: "math",
    layer: 2,
    primitives: ["Write", "FadeIn", "mk_text"],
    defaultParams: {
      title: "贝叶斯推导",
      formula: "P(赢车|换门) = 2/3",
      steps: ["第一次选中汽车概率 = 1/3", "第一次选中山羊概率 = 2/3"],
    },
    paramHelp: { title: "标题", formula: "主公式", steps: "推导步骤字符串数组" },
  },
  {
    id: "manim_simulation_chart",
    label: "模拟实验图表",
    desc: "蒙特卡洛胜率收敛曲线",
    category: "math",
    layer: 2,
    primitives: ["make_axes", "plot", "DashedLine"],
    defaultParams: {
      title: "蒙特卡洛模拟",
      trials: 10000,
      chartType: "line",
      targetValue: 0.666,
      description: "模拟胜率收敛到 66.6%",
    },
    paramHelp: {
      title: "标题",
      trials: "模拟次数（展示用）",
      targetValue: "目标收敛值 0~1",
      description: "底部说明文字",
    },
  },
  {
    id: "manim_cardioid",
    label: "心形线",
    desc: "极坐标心形线 r = 1 - cos θ",
    category: "math",
    layer: 2,
    primitives: ["polar curve", "Create", "apply_scene_theme"],
    defaultParams: { title: "心形线", subtitle: "r = 1 - cos θ" },
    paramHelp: { title: "标题", subtitle: "底部公式说明" },
  },
  {
    id: "manim_rose_curve",
    label: "玫瑰线",
    desc: "玫瑰曲线 r = sin(kθ)",
    category: "math",
    layer: 2,
    primitives: ["polar curve", "Create"],
    defaultParams: { title: "玫瑰线", k: 5, subtitle: "r = sin(kθ)" },
    paramHelp: { title: "标题", k: "花瓣参数 k", subtitle: "公式说明" },
  },
  {
    id: "manim_archimedean_spiral",
    label: "阿基米德螺线",
    desc: "r = a + bθ",
    category: "math",
    layer: 2,
    primitives: ["polar curve", "Create"],
    defaultParams: { title: "阿基米德螺线", a: 0.15, b: 0.12, subtitle: "r = a + bθ" },
    paramHelp: { title: "标题", a: "起始半径 a", b: "增长率 b" },
  },
  {
    id: "manim_exponential_spiral",
    label: "指数螺线",
    desc: "r = a·e^(bθ)",
    category: "math",
    layer: 2,
    primitives: ["polar curve", "Create"],
    defaultParams: { title: "指数螺线", a: 0.08, b: 0.18, subtitle: "r = a·e^(bθ)" },
    paramHelp: { title: "标题", a: "系数 a", b: "指数系数 b" },
  },
  {
    id: "manim_lemniscate",
    label: "莱姆尼斯盖特",
    desc: "∞ 形对称曲线",
    category: "math",
    layer: 2,
    primitives: ["parametric curve", "Create"],
    defaultParams: { title: "莱姆尼斯盖特", a: 2.0, subtitle: "(x²+y²)² = a²(x²-y²)" },
    paramHelp: { title: "标题", a: "尺度参数 a" },
  },
  {
    id: "manim_cycloid",
    label: "摆线",
    desc: "轮子滚动时轮缘轨迹",
    category: "math",
    layer: 2,
    primitives: ["parametric curve", "Create"],
    defaultParams: { title: "摆线", a: 0.55, subtitle: "轮子滚动轨迹" },
    paramHelp: { title: "标题", a: "轮半径系数" },
  },
  {
    id: "manim_lissajous",
    label: "李萨如图形",
    desc: "x=sin(aθ), y=sin(bθ)",
    category: "math",
    layer: 2,
    primitives: ["parametric curve", "Create"],
    defaultParams: { title: "李萨如图形", a: 3, b: 4, subtitle: "x=sin(aθ), y=sin(bθ)" },
    paramHelp: { title: "标题", a: "x 频率", b: "y 频率" },
  },
  {
    id: "manim_lorenz_attractor",
    label: "洛伦兹吸引子",
    desc: "混沌系统三维蝴蝶轨迹（OpenGL）",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Create", "ambient rotation"],
    defaultParams: {
      title: "洛伦兹吸引子",
      subtitle: "混沌中的蝴蝶",
      n: 3,
      colors: ["#e85d75", "#4a90d9", "#50c878"],
    },
    paramHelp: {
      title: "标题",
      subtitle: "底部说明",
      n: "轨迹条数 1-16",
      colors: "十六进制颜色数组，如 [\"#e85d75\", \"#4a90d9\"]",
      initial_conditions: "可选 [[x,y,z], ...] 自定义初值",
      perturbation: "无 initial_conditions 时，沿 x 轴扰动间距，默认 0.35",
    },
  },
  {
    id: "manim_mandelbrot_zoom",
    label: "曼德布罗集",
    desc: "分形边界静态图 + 放大",
    category: "math",
    layer: 2,
    primitives: ["ImageMobject", "numpy", "scale"],
    defaultParams: { title: "曼德布罗集", subtitle: "z_{n+1} = z_n² + c" },
    paramHelp: { title: "标题", subtitle: "迭代公式说明" },
  },
  {
    id: "manim_custom",
    label: "数学宇宙（万能 scene）",
    desc: "params.scene 指定场景名（CardioidScene、LorenzScene 等），无需逐个注册 type",
    category: "advanced",
    layer: 3,
    primitives: ["math_universe registry", "apply_scene_theme"],
    defaultParams: {
      scene: "LorenzScene",
      title: "洛伦兹吸引子",
      subtitle: "混沌中的蝴蝶",
      n: 3,
      colors: ["#e85d75", "#4a90d9", "#50c878"],
    },
    paramHelp: {
      scene: "场景类名，见 GET /api/manim/universe-scenes",
      title: "标题",
      subtitle: "底部说明",
      n: "LorenzScene：轨迹条数 1-16",
      colors: "LorenzScene：颜色数组",
      initial_conditions: "LorenzScene：[[x,y,z], ...] 初值",
    },
  },
  {
    id: "manim_curve_3d",
    label: "3D 空间曲线",
    desc: "ThreeDAxes + 螺旋上升轨迹",
    category: "math",
    layer: 2,
    primitives: ["ThreeDScene", "ParametricFunction"],
    defaultParams: { title: "3D 空间曲线", t_max: 20 },
    paramHelp: { title: "标题", t_max: "参数 t 上限" },
  },
  {
    id: "manim_parametric_surface",
    label: "3D 参数曲面",
    desc: "Surface u,v → (u, v, sin(u)cos(v))",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "Surface"],
    defaultParams: { title: "参数曲面" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_parametric_curve",
    label: "通用 2D 参数曲线",
    desc: "内外摆线等参数曲线骨架",
    category: "math",
    layer: 2,
    primitives: ["ParametricFunction", "build_parametric"],
    defaultParams: { title: "参数曲线" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_rossler",
    label: "Rössler 吸引子",
    desc: "混沌吸引子 3D 轨迹",
    category: "media",
    layer: 2,
    primitives: ["ThreeDScene", "VMobject"],
    defaultParams: { title: "Rössler 吸引子" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_julia_set",
    label: "朱利亚集",
    desc: "Julia 分形图像",
    category: "math",
    layer: 2,
    primitives: ["ImageMobject", "julia_rgba"],
    defaultParams: { title: "朱利亚集", c_real: -0.7, c_imag: 0.27015 },
    paramHelp: { title: "标题", c_real: "c 实部", c_imag: "c 虚部" },
  },
  {
    id: "manim_koch_snowflake",
    label: "Koch 雪花",
    desc: "Koch 分形曲线",
    category: "math",
    layer: 2,
    primitives: ["VMobject", "recursive"],
    defaultParams: { title: "Koch 雪花", depth: 4 },
    paramHelp: { title: "标题", depth: "递归深度 1-5" },
  },
  {
    id: "manim_three_body",
    label: "三体问题",
    desc: "三质点引力轨迹动画",
    category: "math",
    layer: 2,
    primitives: ["Dot", "TracedPath", "simulation"],
    defaultParams: { title: "三体问题", steps: 800 },
    paramHelp: { title: "标题", steps: "模拟步数" },
  },
  {
    id: "manim_outline",
    label: "大纲结构图",
    desc: "章节树状大纲逐层写出",
    category: "infographic",
    layer: 2,
    primitives: ["Write", "LaggedStart", "mk_title"],
    defaultParams: { title: "建立脑内索引系统" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_teacher_resources",
    label: "老师资源图",
    desc: "讲义、笔记、考古题汇聚考点方向",
    category: "infographic",
    layer: 2,
    primitives: ["Rectangle", "Arrow", "Circle"],
    defaultParams: { title: "老师的重点就是考点" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_draw_diagram",
    label: "结构绘制",
    desc: "画图理解复杂结构（示意双腔 + 导管）",
    category: "infographic",
    layer: 2,
    primitives: ["Circle", "Line", "Arrow", "Create"],
    defaultParams: { title: "画出复杂结构" },
    paramHelp: { title: "标题" },
  },
  {
    id: "manim_compare_table",
    label: "左右对比表",
    desc: "易混淆概念并列比较",
    category: "infographic",
    layer: 2,
    primitives: ["VGroup", "FadeIn", "mk_text"],
    defaultParams: {
      title: "水溶性 vs 脂溶性",
      left_title: "水溶性养分",
      right_title: "脂溶性养分",
      left_items: ["易吸收", "直接进入血液", "不需载体"],
      right_items: ["吸收较慢", "需载体蛋白", "储存在脂肪组织"],
    },
    paramHelp: {
      title: "标题",
      left_title: "左栏标题",
      right_title: "右栏标题",
      left_items: "左栏条目数组",
      right_items: "右栏条目数组",
    },
  },
  {
    id: "manim_vocabulary_focus",
    label: "单字放大",
    desc: "从模糊页聚焦到单个词汇反复强调",
    category: "infographic",
    layer: 2,
    primitives: ["Transform", "scale", "Indicate"],
    defaultParams: { title: "单字击破法", word: "Betray", blur_text: "一整页单字……" },
    paramHelp: { title: "标题", word: "聚焦单词", blur_text: "背景模糊文字" },
  },
  {
    id: "manim_multi_explanation",
    label: "多人解释",
    desc: "同学与老师不同讲法气泡",
    category: "infographic",
    layer: 2,
    primitives: ["RoundedRectangle", "FadeIn"],
    defaultParams: {
      title: "不同讲法带来不同理解",
      question: "这题到底怎么解？",
      labels: ["同学 A 的解释", "同学 B 的解释", "老师的解释"],
    },
    paramHelp: { title: "标题", question: "中心问题", labels: "三个解释者标签" },
  },
  {
    id: "manim_explanation_highlight",
    label: "详解高亮",
    desc: "详解关键字框选 + Indicate",
    category: "infographic",
    layer: 2,
    primitives: ["SurroundingRectangle", "Indicate"],
    defaultParams: { title: "详解中的关键字", keywords: "活化能 · 催化剂 · 反应路径" },
    paramHelp: { title: "标题", keywords: "要高亮的关键字串" },
  },
  {
    id: "manim_recall_page",
    label: "翻页复述",
    desc: "阅读页 +「我学到了什么？」自问气泡",
    category: "infographic",
    layer: 2,
    primitives: ["Rectangle", "RoundedRectangle"],
    defaultParams: {
      title: "即时检核机制",
      page_text: "主动运输：ATP → ADP",
      prompt: "我学到了什么？",
    },
    paramHelp: { title: "标题", page_text: "页面内容", prompt: "自问提示" },
  },
  {
    id: "manim_phone_fade",
    label: "手机淡出",
    desc: "手机缩小淡出 + 习惯时间线",
    category: "infographic",
    layer: 2,
    primitives: ["Square", "set_opacity", "scale"],
    defaultParams: { title: "减少干扰", timeline: "半天 → 一天 → 两天" },
    paramHelp: { title: "标题", timeline: "习惯养成时间线文字" },
  },
  {
    id: "manim_keybook",
    label: "考前重点本",
    desc: "厚书压缩成薄本 + 易忘点列表",
    category: "infographic",
    layer: 2,
    primitives: ["Transform", "Rectangle"],
    defaultParams: {
      title: "考前只看这一本",
      keywords: ["易忘点 1", "易忘点 2", "易忘点 3"],
    },
    paramHelp: { title: "标题", keywords: "易忘点字符串数组" },
  },
  {
    id: "manim_moving_frame_box",
    label: "公式框选",
    desc: "官方 MovingFrameBox：分段 MathTex + SurroundingRectangle 切换高亮",
    category: "math",
    layer: 2,
    primitives: ["MathTex", "SurroundingRectangle", "ReplacementTransform"],
    officialExample: { title: "MovingFrameBox", url: DOC },
    defaultParams: {
      title: "乘积求导法则",
      parts: [
        "\\frac{d}{dx}f(x)g(x)=",
        "f(x)\\frac{d}{dx}g(x)",
        "+",
        "g(x)\\frac{d}{dx}f(x)",
      ],
      highlight_indices: [1, 3],
      frame_buff: 0.12,
      title_font_size: 32,
      formula_font_size: 42,
      hold_seconds: 0.8,
      run_times: { title: 0.5, write: 1.2, box_create: 0.8, box_switch: 0.5, between: 0.4 },
    },
    paramHelp: {
      title: "标题（中文，走 cjk_font）",
      parts: "MathTex 分段 LaTeX 数组",
      highlight_indices: "框选下标，如 [1, 3]",
      frame_color: "框线颜色 hex",
      frame_buff: "SurroundingRectangle buff，默认 0.12",
      title_font_size: "标题字号",
      formula_font_size: "公式字号",
      hold_seconds: "结尾停留秒数",
      run_times: "动画时长对象：title/write/box_create/box_switch/between",
    },
  },
  {
    id: "manim_point_with_trace",
    label: "动点轨迹",
    desc: "官方 PointWithTrace：旋转/平移留痕；mode=parametric 沿 x(t),y(t) 绘轨迹",
    category: "math",
    layer: 2,
    primitives: ["VMobject", "add_updater", "Rotating", "ValueTracker"],
    officialExample: { title: "PointWithTrace", url: DOC },
    defaultParams: {
      title: "动点留轨迹",
      mode: "demo",
      moves: [[0, 1, 0], [-1, 0, 0]],
      trace_stroke_width: 3,
      rotate_angle: 3.141592653589793,
      rotate_about: "RIGHT",
      run_times: { title: 0.5, rotate: 2, move: 1, guide: 1, trace: 4, pause: 0.3 },
    },
    paramHelp: {
      mode: "demo | parametric",
      x: "parametric：x(t) 表达式",
      y: "parametric：y(t) 表达式",
      t_min: "参数下限",
      t_max: "参数上限",
      moves: "demo 位移 [[dx,dy,dz], ...]",
      move_run_times: "demo 每段位移秒数数组（可选）",
      rotate_angle: "demo 旋转弧度",
      rotate_about: "RIGHT|LEFT|UP|ORIGIN 或 [x,y,z]",
      trace_stroke_width: "轨迹线宽",
      guide_opacity: "parametric 引导线透明度",
      run_times: "title/rotate/move/guide/trace/pause",
      hold_seconds: "结尾停留",
    },
  },
  {
    id: "manim_vector_arrow",
    label: "向量箭头",
    desc: "官方 VectorArrow：坐标平面 + 向量 + 端点标注",
    category: "math",
    layer: 2,
    primitives: ["NumberPlane", "Arrow", "Dot", "Text"],
    officialExample: { title: "VectorArrow", url: DOC },
    defaultParams: {
      title: "向量与坐标",
      arrow_start: [0, 0, 0],
      arrow_end: [2, 2, 0],
      origin_text: "(0, 0)",
      tip_text: "(2, 2)",
      show_plane: true,
      plane_x_range: [-7, 7, 1],
      plane_y_range: [-4, 4, 1],
      label_font_size: 24,
      run_times: { title: 0.5, diagram: 1.2 },
    },
    paramHelp: {
      arrow_start: "箭头起点 [x,y,z]",
      arrow_end: "箭头终点 [x,y,z]",
      origin_text: "起点标注文字",
      tip_text: "终点标注文字",
      origin_label_dir: "起点标注方向 DOWN|UP|LEFT|RIGHT",
      tip_label_dir: "终点标注方向",
      plane_x_range: "平面 x 范围 [min,max,step]",
      plane_y_range: "平面 y 范围",
      label_font_size: "标注字号",
      run_times: "title/diagram",
    },
  },
  {
    id: "manim_brace_annotation",
    label: "括号标注",
    desc: "官方 BraceAnnotation：线段 + Brace 文字/公式",
    category: "math",
    layer: 2,
    primitives: ["Brace", "Line", "Dot", "get_text", "get_tex"],
    officialExample: { title: "BraceAnnotation", url: DOC },
    defaultParams: {
      title: "距离标注",
      dot1: [-2, -1, 0],
      dot2: [2, 1, 0],
      horizontal_label: "Horizontal distance",
      formula_label: "x-x_1",
      show_formula_brace: true,
      line_stroke_width: 4,
      label_font_size: 22,
      run_times: { title: 0.5, diagram: 1.5 },
    },
    paramHelp: {
      dot1: "起点 [x,y,z]",
      dot2: "终点 [x,y,z]",
      horizontal_label: "水平 Brace 文字",
      formula_label: "斜 Brace LaTeX（texlive）",
      show_formula_brace: "是否显示公式 Brace",
      line_color: "线段颜色 hex",
      line_stroke_width: "线宽",
      label_font_size: "标注字号",
      run_times: "title/diagram",
    },
  },
  {
    id: "manim_sin_cos_plot",
    label: "正弦余弦图",
    desc: "官方 SinAndCosFunctionPlot：可配置 sin/cos 表达式与坐标",
    category: "math",
    layer: 2,
    primitives: ["Axes", "plot", "get_vertical_line"],
    officialExample: { title: "SinAndCosFunctionPlot", url: DOC },
    defaultParams: {
      title: "sin(x) 与 cos(x)",
      sin_expr: "sin(x)",
      cos_expr: "cos(x)",
      sin_label: "sin(x)",
      cos_label: "cos(x)",
      x_range: [-10, 10.3, 1],
      y_range: [-1.5, 1.5, 1],
      x_length: 10,
      y_length: 5,
      show_vertical_line: true,
      vertical_at: 6.283185307179586,
      vertical_label: "x=2π",
      label_font_size: 22,
      run_times: { title: 0.5, axes: 1, curves: 1.2, vertical: 0.6 },
    },
    paramHelp: {
      sin_expr: "正弦曲线 y=f(x)，如 sin(x)",
      cos_expr: "余弦曲线表达式",
      x_range: "坐标轴 x [min,max,step]",
      y_range: "坐标轴 y [min,max,step]",
      plot_x_min: "绘图 x 下限（默认同 x_range）",
      plot_x_max: "绘图 x 上限",
      vertical_at: "竖线 x 位置（默认 2π）",
      vertical_label: "竖线标注",
      x_length: "轴显示宽度",
      y_length: "轴显示高度",
      run_times: "title/axes/curves/vertical",
    },
  },
  {
    id: "manim_point_on_path",
    label: "路径动点",
    desc: "官方 PointMovingOnShapes：圆上 MoveAlongPath + 旋转",
    category: "math",
    layer: 2,
    primitives: ["Circle", "MoveAlongPath", "Rotating", "GrowFromCenter"],
    officialExample: { title: "PointMovingOnShapes", url: DOC },
    defaultParams: {
      title: "沿路径运动",
      circle_center: [0, 0, 0],
      circle_radius: 1,
      line_start: [3, 0, 0],
      line_end: [5, 0, 0],
      transform_shift: [1, 0, 0],
      rotate_about: [2, 0, 0],
      run_times: { title: 0.5, grow: 1, transform: 0.8, path: 2, rotate: 1.5 },
    },
    paramHelp: {
      circle_center: "圆心 [x,y,z]",
      circle_radius: "圆半径",
      line_start: "辅助线段起点",
      line_end: "辅助线段终点",
      transform_shift: "Transform 位移",
      rotate_about: "旋转中心 [x,y,z]",
      run_times: "grow/transform/path/rotate",
    },
  },
  {
    id: "manim_moving_angle",
    label: "动态角度",
    desc: "官方 MovingAngle：ValueTracker 驱动 θ",
    category: "math",
    layer: 2,
    primitives: ["Angle", "ValueTracker", "add_updater"],
    officialExample: { title: "MovingAngle", url: DOC },
    defaultParams: {
      title: "角度变化",
      theta_start: 110,
      theta_mid: 40,
      theta_increment: 140,
      theta_end: 350,
      rotation_center: "LEFT",
      line_half_length: 3,
      angle_radius: 0.5,
      formula_font_size: 32,
      run_times: { to_mid: 1.2, increment: 1.2, color_flash: 0.5, to_end: 1.5 },
    },
    paramHelp: {
      theta_start: "起始角（度）",
      theta_mid: "第一次目标角",
      theta_increment: "中间增量（官方 140）",
      theta_end: "结束角",
      rotation_center: "LEFT|RIGHT|ORIGIN 或 [x,y,z]",
      line_half_length: "线段半长",
      angle_radius: "角弧半径",
      theta_label: "角标 LaTeX，默认 \\theta",
      run_times: "to_mid/increment/color_flash/to_end/intro_wait",
    },
  },
  {
    id: "manim_sine_unit_circle",
    label: "单位圆正弦",
    desc: "官方 SineCurveUnitCircle：单位圆推导正弦曲线",
    category: "math",
    layer: 2,
    primitives: ["Circle", "add_updater", "always_redraw"],
    officialExample: { title: "SineCurveUnitCircle", url: DOC },
    defaultParams: {
      title: "单位圆与正弦曲线",
      origin_x: -4,
      circle_radius: 1,
      x_axis_start: -6,
      x_axis_end: 6,
      curve_x_scale: 4,
      orbit_rate: 0.25,
      run_seconds: 8,
    },
    paramHelp: {
      origin_x: "圆心 x",
      circle_radius: "圆半径",
      x_axis_start: "x 轴起点",
      x_axis_end: "x 轴终点",
      y_axis_half: "y 轴半长",
      curve_x_scale: "正弦曲线水平拉伸系数",
      orbit_rate: "绕圆速度基准",
      run_seconds: "动画总秒数",
    },
  },
  {
    id: "manim_boolean_ops",
    label: "布尔运算",
    desc: "官方 BooleanOperations：椭圆交/并/差/补",
    category: "math",
    layer: 2,
    primitives: ["Intersection", "Union", "Exclusion", "Difference"],
    officialExample: { title: "BooleanOperations", url: DOC },
    defaultParams: {
      header_label: "Boolean Operation",
      operations: ["intersection", "union", "exclusion", "difference"],
      ellipse_width: 4,
      ellipse_height: 5,
      ellipse1_shift: [-2.5, 0, 0],
      ellipse2_shift: [0.5, 0, 0],
      result_scale: 0.35,
      result_position: [4, 1.5, 0],
      run_times: { base: 1, op: 0.8, label: 0.5 },
    },
    paramHelp: {
      operations: "intersection|union|exclusion|difference 子集",
      ellipse_width: "椭圆宽",
      ellipse_height: "椭圆高",
      ellipse1_shift: "椭圆1 位置 [x,y,z]",
      ellipse2_shift: "椭圆2 位置",
      result_scale: "结果图形缩放",
      result_position: "结果图形位置",
      stroke_width: "椭圆描边宽",
      fill_opacity: "填充透明度",
      run_times: "base/op/label",
    },
  },
  {
    id: "manim_following_camera",
    label: "相机跟随",
    desc: "官方 FollowingGraphCamera：可配置曲线表达式与相机缩放",
    category: "math",
    layer: 2,
    primitives: ["MovingCameraScene", "MoveAlongPath", "Restore"],
    officialExample: { title: "FollowingGraphCamera", url: DOC },
    defaultParams: {
      title: "相机跟随曲线",
      curve_expr: "sin(x)",
      x_range: [-1, 10, 1],
      y_range: [-1.5, 1.5, 1],
      curve_x_min: 0,
      curve_x_max: 9.42477796076938,
      camera_scale: 0.55,
      restore_camera: true,
      follow_run_time: 4,
      run_times: { zoom: 1, follow: 4, restore: 1 },
    },
    paramHelp: {
      curve_expr: "曲线 y=f(x)，如 sin(x)",
      x_range: "坐标轴 x [min,max,step]",
      y_range: "坐标轴 y",
      curve_x_min: "曲线绘制 x 起点",
      curve_x_max: "曲线绘制 x 终点（默认 3π）",
      camera_scale: "跟拍前相机缩放（官方 0.5）",
      restore_camera: "结束后是否 Restore 相机",
      follow_run_time: "跟拍秒数（同 run_times.follow）",
      run_times: "zoom/follow/restore",
    },
  },
  {
    id: "manim_graph_area",
    label: "曲线面积",
    desc: "官方 GraphAreaPlot：可配置曲线表达式、黎曼和与面积区间",
    category: "math",
    layer: 2,
    primitives: ["get_riemann_rectangles", "get_area", "plot"],
    officialExample: { title: "GraphAreaPlot", url: DOC },
    defaultParams: {
      title: "曲线与面积",
      curve_1_expr: "4*x - x**2",
      curve_2_expr: "0.8*x**2 - 3*x + 4",
      curve_x_range: [0, 4],
      vertical_lines_at: [2, 3],
      riemann_x_range: [0.3, 0.6],
      riemann_dx: 0.03,
      area_x_range: [2, 3],
      x_max: 5,
      y_max: 6,
    },
    paramHelp: {
      curve_1_expr: "曲线1 y=f(x)",
      curve_2_expr: "曲线2 y=g(x)",
      curve_x_range: "曲线绘制 x [min,max]",
      vertical_lines_at: "竖线 x 坐标数组，如 [2,3]",
      riemann_x_range: "黎曼和区间 [a,b]",
      riemann_dx: "黎曼矩形宽度",
      area_x_range: "两曲线间面积 x 区间",
      x_max: "坐标轴 x 上限",
      y_max: "坐标轴 y 上限",
      riemann_opacity: "黎曼填充透明度",
      area_opacity: "面积填充透明度",
    },
  },
  {
    id: "manim_heat_diagram",
    label: "热图折线",
    desc: "官方 HeatDiagramPlot：折线热力学示意",
    category: "math",
    layer: 2,
    primitives: ["plot_line_graph", "Axes"],
    officialExample: { title: "HeatDiagramPlot", url: DOC },
    defaultParams: {
      title: "热图示意",
      x_vals: [0, 8, 38, 39],
      y_vals: [20, 0, 0, -5],
      x_range: [0, 40, 5],
      y_range: [-8, 32, 5],
      x_length: 9,
      y_length: 6,
      x_label: "ΔQ",
      y_label: "T(°C)",
      label_font_size: 22,
      run_times: { axes: 1, graph: 1.2 },
    },
    paramHelp: {
      x_vals: "折线 x 数组",
      y_vals: "折线 y 数组",
      x_range: "坐标轴 x [min,max,step]",
      y_range: "坐标轴 y",
      x_length: "轴宽",
      y_length: "轴高",
      x_label: "x 轴标签",
      y_label: "y 轴标签",
      label_font_size: "轴标签字号",
      run_times: "axes/graph",
    },
  },
  {
    id: "formula_curve",
    label: "公式曲线生成器",
    desc: "输入 x(t),y(t) 或 r(t) 公式自动生成曲线动画",
    category: "math",
    layer: 2,
    primitives: ["ParametricFunction", "build_parametric", "eval_curve_expr"],
    defaultParams: {
      title: "谐波叠加",
      mode: "parametric_2d",
      x: "sin(3*t) + 0.5*sin(5*t)",
      y: "cos(4*t) + 0.5*cos(6*t)",
      t_min: 0,
      t_max: 20,
      curve_run_time: 5,
      hold_seconds: 3,
    },
    paramHelp: {
      mode: "parametric_2d | polar_2d | parametric_3d",
      x: "x(t) 表达式",
      y: "y(t) 表达式",
      z: "z(t) 表达式（3D）",
      r: "r(t) 极坐标表达式",
      t_min: "参数下限",
      t_max: "参数上限",
      hold_seconds: "结尾停留秒数",
      rotate_seconds: "3D 旋转秒数",
    },
  },
  {
    id: "custom_dsl",
    label: "JSON 场景 DSL",
    desc: "用 JSON 描述对象与动画序列（第三层）",
    category: "advanced",
    layer: 3,
    primitives: ["JSON-driven", "FadeIn", "Create", "Write", "GrowArrow"],
    officialExample: { title: "Manim examples", url: DOC },
    defaultParams: {
      title: "DSL Demo",
      objects: [
        { id: "c1", type: "circle", radius: 1, color: "BLUE" },
        { id: "t1", type: "text", content: "Hello Manim", shift: [0, -2, 0] },
      ],
      timeline: [
        { action: "create", target: "c1" },
        { action: "write", target: "t1" },
        { action: "wait", duration: 0.5 },
      ],
    },
    paramHelp: {
      title: "场景标题",
      objects: "对象列表 type: circle|rect|text|arrow|dot",
      timeline: "动画序列 action: create|fade_in|write|grow_arrow|wait|transform",
    },
  },
  {
    id: "custom_python",
    label: "自定义 Python Scene",
    desc: "粘贴 Manim Scene 代码（参考官方示例）",
    category: "advanced",
    layer: 3,
    primitives: ["Scene", "construct", "任意 Manim API"],
    officialExample: { title: "Official examples", url: DOC },
    defaultParams: {
      class_name: "HarmonicRibbon3D",
      code:
        "class HarmonicRibbon3D(ThreeDScene):\n" +
        "    def construct(self):\n" +
        "        axes = ThreeDAxes()\n" +
        "        self.add(axes)\n" +
        "        self.set_camera_orientation(phi=65*DEGREES, theta=45*DEGREES)\n" +
        "        def curve(t):\n" +
        "            x = np.sin(2*t) + 0.3*np.sin(5*t)\n" +
        "            y = np.cos(3*t) + 0.3*np.cos(7*t)\n" +
        "            z = 0.6*np.sin(4*t)\n" +
        "            return np.array([x, y, z])\n" +
        "        graph = ParametricFunction(curve, t_range=[0, 20], color=YELLOW)\n" +
        "        self.play(Create(graph, rate_func=linear), run_time=6)\n",
    },
    paramHelp: {
      class_name: "Scene 类名（ThreeDScene 时必填且与 class 一致）",
      code: "Scene 类定义；可省略 from manim import * / import numpy",
      renderer: "可选 opengl | cairo；ThreeDScene 通常自动 opengl",
    },
  },
];

export function getCapability(id: string): ManimCapability | undefined {
  return MANIM_CAPABILITIES.find((c) => c.id === id);
}

export function getExampleParams(id: string): Record<string, unknown> {
  const cap = getCapability(id);
  return cap ? JSON.parse(JSON.stringify(cap.defaultParams)) : {};
}

/** 按成熟应用场景筛选模板 */
export function getCapabilitiesByDomain(domain: ManimDomain | "all"): ManimCapability[] {
  if (domain === "all") return MANIM_CAPABILITIES;
  return MANIM_CAPABILITIES.filter((c) => getTemplateDomain(c.id) === domain);
}
